name: Build 2024.3 for Windows

on: [workflow_dispatch, pull_request]

jobs:
  run_win:
    runs-on: windows-latest
    name: Build on Windows

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Clone
      run: |
        git clone https://github.com/openvinotoolkit/openvino_contrib -b releases/2024/3 --depth 1
        git clone https://github.com/openvinotoolkit/testdata
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'

    - name: Download OpenVINO
      run: |
        Invoke-WebRequest https://storage.openvinotoolkit.org/repositories/openvino/packages/2024.3/windows/w_openvino_toolkit_windows_2024.3.0.16041.1e3b88e4e3f_x86_64.zip -OutFile openvino.zip
        Expand-Archive -Path openvino.zip -DestinationPath "C:\Program Files (x86)\Intel"
        Move-Item -Path "C:\Program Files (x86)\Intel\w_openvino_toolkit_windows_2024.3.0.16041.1e3b88e4e3f_x86_64" -Destination "C:\Program Files (x86)\Intel\openvino"
      shell: pwsh

    - name: Build bindings
      run: |
        mkdir build_api && cd build_api
        call "C:\Program Files (x86)\Intel\openvino\setupvars.bat"
        cmake ..\openvino_contrib\modules\java_api -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release -j 2
        move Release\\*.dll "C:\Program Files (x86)\Intel\openvino\runtime\bin\intel64\Release"
      shell: cmd

    - name: Build package
      run: |
        call "C:\Program Files (x86)\Intel\openvino\setupvars.bat"
        gradle clean build --info
        gradle test -Prun_tests -DMODELS_PATH=..\\..\\..\\testdata -Ddevice=CPU --info
      shell: cmd
      working-directory: openvino_contrib\\modules\\java_api

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "pkg_win"
        path: "openvino_contrib\\modules\\java_api\\build\\libs\\*.jar"
